import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:new_app/components/caraousel.dart';
import 'package:new_app/models/lyrics.dart';
import 'package:http/http.dart' as http;

class ViewLyrics extends StatefulWidget {
  final String passedArtist;
  final String passedTitle;

  const ViewLyrics(
      {Key? key, required this.passedArtist, required this.passedTitle})
      : super(key: key);

  @override
  _ViewLyricsState createState() => _ViewLyricsState();
}

class _ViewLyricsState extends State<ViewLyrics> {
  late Future<Autogenerated> futureLyrics;
  Future<Autogenerated> fetchLyrics() async {
    final response = await http.get(Uri.parse(
        'https://lyrics-finder-node.herokuapp.com/lyrics?title=' +
            widget.passedTitle +
            " " +
            widget.passedArtist));

    if (response.statusCode == 200) {
      // If the server did return a 200 OK response,
      // then parse the JSON.
      print(response.body);
      return Autogenerated.fromJson(jsonDecode(response.body));
    } else {
      // If the server did not return a 200 OK response,
      // then throw an exception.
      throw Exception('Failed to load album');
    }
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    futureLyrics = fetchLyrics();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
            margin: EdgeInsets.all(24),
            child: Column(
              children: [
                Row(
                  children: [
                    GestureDetector(
                        onTap: () {
                          Navigator.pop(context);
                        },
                        child: const Image(
                            image: AssetImage("img/back_arrow_icon.png"))),
                    Expanded(
                      child: Container(
                        margin: const EdgeInsets.only(left: 40),
                        child: Text(
                          "Lyrics for " +
                              widget.passedTitle +
                              " by " +
                              widget.passedArtist,
                          style: const TextStyle(
                              fontSize: 20, fontWeight: FontWeight.bold),
                        ),
                      ),
                    ),
                  ],
                ),
                const SizedBox(
                  height: 30,
                ),
                Container(
                    alignment: Alignment.centerLeft,
                    margin: EdgeInsets.only(left: 30),
                    child: FutureBuilder<Autogenerated>(
                      future: futureLyrics,
                      builder: (context, AsyncSnapshot snapshot) {
                        if (snapshot.hasData) {
                          return Text(
                            snapshot.data!.result,
                            style: TextStyle(fontSize: 20),
                          );
                        } else if (snapshot.hasError) {
                          return Text("${snapshot.error}");
                        } else {
                          return Center(
                            child: CircularProgressIndicator(),
                          );
                        }
                      },
                    ))
              ],
            ),
          ),
        ),
      ),
    );
  }
}
