class Autogenerated {
  String? urlParameter;
  String? result;

  Autogenerated({this.urlParameter, this.result});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    urlParameter = json['urlParameter'];
    result = json['result'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['urlParameter'] = this.urlParameter;
    data['result'] = this.result;
    return data;
  }
}
